//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Product
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage = "you must fill user name")]
        [MaxLength(10, ErrorMessage = "Max Characters are 10")]
        [MinLength(3, ErrorMessage = "Min Characters are 3")]

        public string ProductName { get; set; }
        [Required(ErrorMessage = "you must fill price")]
        [Range(1,999999999999.99,ErrorMessage ="Invaild Price")]
        public Nullable<double> ProductPrice { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
