//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "you must fill user name")]
        [MaxLength(10, ErrorMessage = "Max Characters are 10")]
        [MinLength(3, ErrorMessage = "Min Characters are 3")]

        public string UserName { get; set; }
        [Required(ErrorMessage = "you must fill password")]
        [MinLength(6, ErrorMessage = "Min Length is 6 Characters")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }
        [Required(ErrorMessage = "you must fill email")]
        [DataType(DataType.EmailAddress,ErrorMessage ="E-Mail is not Vaild")]
        public string UserEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
